name: Update TC Repo File

on:
  workflow_dispatch:

jobs:
  update-tc-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Utility repo
        uses: actions/checkout@v3

      - name: Clone TC-Repo
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git clone https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/saran178/TC-Repo.git

      - name: Edit sample.txt
        run: |
          echo "Updated by GitHub Actions on $(date -u)" >> TC-Repo/sample.txt

      - name: Commit and push changes to TC-Repo
        working-directory: TC-Repo
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.email "saravanan.i@intelizign.com"
          git config --global user.name "saran"
          git add sample.txt
          git commit -m "Update sample.txt via GitHub Actions"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/saran178/TC-Repo.git main
