name: Update Another Repo File

on:
  workflow_dispatch:  # Manual trigger, easy to test

jobs:
  update-external-repo:
    runs-on: ubuntu-latest  # or windows-latest if you prefer

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3

      - name: Clone external repo
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git clone https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/saran178/TC-Repo.git

      - name: Edit file in external repo
        run: |
          echo "Appending date to sample.txt"
          echo "Updated by GitHub Actions on $(date -u)" >> TC-Repo/sample.txt

      - name: Commit and push changes to external repo
        working-directory: TC-Repo
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add sample.txt
          git commit -m "Update sample.txt via GitHub Actions"
          git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/saran178/TC-Repo.git main
